version: '3.7'
services:
  postgres:
    image: library/postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=login
      - POSTGRES_PASSWORD=parol